services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: blog-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U ${DB_USER} -P ${DB_PASSWORD} -Q 'SELECT 1' -b -C"]
      interval: 10s
      timeout: 3s
      retries: 10
      # Healthcheck'i tamamen silebilirsin ya da kalsýn, ama API ona bakmasýn.

  api:
    image: alyblt/blog-api:latest  # Docker Hub imaj ismin bu olmalý!
    container_name: blog-api
    ports:
      - "11011:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True
      - JWTSettings__SecretKey=${JWT_SECRET}
      - JWTSettings__Issuer=${JWT_ISSUER}
      - JWTSettings__Audience=${JWT_AUDIENCE}
      - ShowSwagger=${ShowSwagger}
    depends_on:
      db:
        condition: service_started # "service_healthy" yerine "service_started" yaptýk!

volumes:
  sql_data: